"""initial schema

Revision ID: 765ba2da5a11
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '765ba2da5a11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('loyalty_tier', sa.Text(), server_default='standard', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("loyalty_tier IN ('standard','gold','vip')", name=op.f('ck_customers_loyalty_tier_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('email', name=op.f('uq_customers_email'))
    )
    op.create_table('policy_documents',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_documents')),
    sa.UniqueConstraint('version', name=op.f('uq_policy_documents_version'))
    )
    op.create_table('policy_rules',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_rules')),
    sa.UniqueConstraint('key', name=op.f('uq_policy_rules_key'))
    )
    op.create_table('conversations',
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','resolved','escalated')", name=op.f('ck_conversations_status_valid')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_conversations_customer_id_customers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_table('orders',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='placed', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Text(), server_default='USD', nullable=False),
    sa.Column('ordered_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('placed','shipped','partially_delivered','delivered','cancelled')", name=op.f('ck_orders_status_valid')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_orders_total_amount_nonneg')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id_customers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_number', name=op.f('uq_orders_order_number'))
    )
    op.create_index('ix_orders_customer_id', 'orders', ['customer_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('system','user','assistant','tool')", name=op.f('ck_messages_role_valid')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.Text(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_final_sale', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('return_window_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_quantity_positive')),
    sa.CheckConstraint('return_window_days >= 0', name=op.f('ck_order_items_return_window_nonneg')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_order_items_unit_price_nonneg')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_table('agent_steps',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=True),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('model_text','tool_call','tool_result','decision')", name=op.f('ck_agent_steps_type_valid')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_agent_steps_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_agent_steps_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_steps')),
    sa.UniqueConstraint('conversation_id', 'step_no', name='conversation_step_no')
    )
    op.create_index('ix_agent_steps_conversation_id', 'agent_steps', ['conversation_id', 'step_no'], unique=False)
    op.create_table('refunds',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('policy_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('decided_by', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decided_by IN ('agent','human')", name=op.f('ck_refunds_decided_by_valid')),
    sa.CheckConstraint("status IN ('approved','denied','escalated')", name=op.f('ck_refunds_status_valid')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_refunds_amount_nonneg')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_refunds_quantity_positive')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_refunds_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_refunds_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_refunds_order_id_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_refunds_order_item_id_order_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds'))
    )
    op.create_index('ix_refunds_customer_id', 'refunds', ['customer_id'], unique=False)
    op.create_index('ix_refunds_order_id', 'refunds', ['order_id'], unique=False)
    op.create_index('ix_refunds_order_item_id', 'refunds', ['order_item_id'], unique=False)
    op.create_index('ix_refunds_status', 'refunds', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refunds_status', table_name='refunds')
    op.drop_index('ix_refunds_order_item_id', table_name='refunds')
    op.drop_index('ix_refunds_order_id', table_name='refunds')
    op.drop_index('ix_refunds_customer_id', table_name='refunds')
    op.drop_table('refunds')
    op.drop_index('ix_agent_steps_conversation_id', table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_orders_customer_id', table_name='orders')
    op.drop_table('orders')
    op.drop_table('conversations')
    op.drop_table('policy_rules')
    op.drop_table('policy_documents')
    op.drop_table('customers')
    # ### end Alembic commands ###
